### PR TITLE
Ics fixes

### PR DESCRIPTION
**Pull request by Phitherek**
Fix iCal feed for UTF-8 encoding, fix time conversion for DateTime Ruby type, fix exception when title, location or description empty.

### CODE REVIEW

**Comment by Phitherek** [comment]
This fixes the problem outlined in #18

**Comment by Phitherek** [comment]
Fixed according to Travis build. Unfortunately one of the builds seems to be misconfigured.

**Comment by Aupajo** [comment]
@Phitherek Thanks! Is there a test you could add that would make sure we're covering this case properly?

**Comment by Aupajo** [comment]
This has been fixed in `0.1.3.rc1`.

See #28.

**Pull request closed without merging**
